name: operator
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 0.0.1
repository: https://github.com/rrousselGit/operator
issue_tracker: https://github.com/rrousselGit/operator/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^5.0.0
  build: ^2.0.0
  # build_config: ^1.0.0
  # collection: ^1.15.0
  meta: ^1.7.0
  source_gen: ^1.2.0
  operator_annotation: ^2.1.0
  freezed: ^2.1.1
  path: ^1.8.2

dev_dependencies:
#   build_test: ^2.1.5
  build_runner: ^2.1.7
#   test: ^1.20.1
#   matcher: ^0.12.11
#   source_gen_test: ^1.0.2
