name: operator_annotation
description: >
  Annotations for the operator code-generator.
  This package does nothing without operator too.
version: 2.1.0
repository: https://github.com/rrousselGit/operator
issue_tracker: https://github.com/rrousselGit/operator/issues

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.7
  test: ^1.21.0
